### ISSUE TITLE
If Dimple fails, the status remains as green and running

### ISSUE THREAD

**Issue by reskyner** [xchem/XChemExplorer#87] opened 2017-10-17 09:41 UTC
Alex:  should it not update to something more meaningful as red and failed (like for the ligand restraints)?

I'm unsure if this was ever the case. Can @tkrojer or @nelse003 confirm so that I can see if it's something that I've messed up, or whether it's a 'feature request'?

**Comment by nelse003** [comment] 2017-10-24 14:39
I've typically seen that xce will update these flags when update tables from datasource is run, but that is not always the case, some dimple and other failures are not picked up, and reamin as running. This is probably to do with how the failure is picked up.

@tkrojer, can you confirm this?

**Comment by tkrojer** [comment] 2017-10-26 13:04
One of the helper scripts will update the DimpleStatus and is part of the xce_dimple script:
helpers/update_data_source_for_new_dimple_pdb.py
And this script sets DimpleStatus to 'finished' when dimple.mtz is present and to 'failed' if the file is not present. Does anyone have an example of where Dimple failed, but the status remained 'running'? This would make troubeshooting a lot easier.
Another problem is that the database may have been updated by another job and is therefore not accessible for a job which wants to edit it at the same time. But again, if we would have a concrete example then this would be straightforward to find out.
Also, the update_datasource_from_filesystem command will only pick up if dimple.mtz (or dimple.pdb) is present, but will not try to determine if it was successfully ran before. But I could change this if deemed helpful!

**Comment by tkrojer** [comment] 2019-06-26 10:32
Duplicate of #139

**Closed by tkrojer** 2019-06-26 10:32 UTC
Labels: Medium, XChem User Feedback, bug, enhancement, wontfix
