### ISSUE TITLE
Populating missing reflections - done?

### ISSUE THREAD

**Issue by reskyner** [xchem/XChemExplorer#30] opened 2017-09-22 13:58 UTC
No, XCE does not do any manipulations of reflection files anymore! We removed such operations a long time ago. Hence, if this is required, then it should ideally happen in DIMPLE as part of the file preparation.

But since this won’t happen any time soon, I guess we will have to accommodate it.

I won’t be able to do it now, but will send an update on Monday.

Tobias

On 30 Jun 2017, at 16:17, Elliot Nelson 

Tobias/Rachel: Does XCE populate the missing reflections and then re-run refinement.?

Elliot

That error message seems pretty clear to me — you need to populate the missing reflections and then re-run refinement.

I thought XCE did that automatically?

Thanks,
Nick

Hi All,

Ritika is trying a new run of panddas 0.2 @ diamond on OTUB. The error (below) is replicated across multiple datasets if i ignore the first few datasets (using ignore_dataset in pandda.analyse command). The majority of data had been processed sucessfully on panddas 0.1 @ diamond. The Structure factors in the mtz file are given as FWT.

Log attached.

Thanks

Elliot

Error:

############################################## <~~~> ###############################################

------------------------------------->>>

Sorry: Structure factor column "FWT" in dataset OTUB2A-x0216 has missing reflections below 4.0A (some reflections are not present in the miller set). 2 reflections are missing from the miller set in the reflection file. You should add these missing reflections and populate the structure factors for these reflections with their estimated values. Analysing maps with missing reflections (escepially low resolution reflections!) will degrade the quality of the analysis. I really would not do this, but you can continue by setting checks.low_resolution_completeness to None.

------------------------------------->>>

############################################## &

**Comment by reskyner** [comment] 2017-09-26 13:08
https://github.com/xchem/XChemExplorer/issues/30

**Comment by reskyner** [comment] 2017-09-29 14:30
@nelse003 will check with nick

**Comment by nelse003** [comment] 2017-10-27 08:08
Hi Nick,

Tobias and I have found the cause of our issues with the missing reflections.

In
 
pandda/lib/python/pandda/anlyse/classes.py 
Function: check_loaded_datasets()
Lines 2132-2237

You check the low resolution limit @ 999A, this not taken from the mtzfile (at say 42A). This means that there are sometimes resloutions between the limit of the mtz file and 999A which are not filled in by current processing of the mtz, hence the missing reflections.

Whether this is a bug or a feature we are not sure, but thought it worth mentioning as expanding the resolution limit of a input file is not a common preprocessing step, and that this error would not uniquely occur within XCE.

Assuming this is the preferred state of Pandda, we will add the preprocessing step into XCE. Please check the attached thread/ in with Tobias If my explanation is not clear. If you think it is worth adjusting the low resolution limit as a parameter, let us know as we can switch out any preprocessing.

Apologies again for conflating my description of this error and the xce handling of free.mtz for passing to pandda.export. I will look at this separately.

Thanks

Elliot
From: Tobias Krojer
Sent: 26 October 2017 15:23
To: Elliot Nelson
Cc: Tobias Krojer; Rachael Skyner
Subject: Re: Missing reflections != pandda export free.mtz error

I agree, but (very) reluctantly…

**Comment by nelse003** [comment] 2017-10-27 08:16
It’s definitely a feature and I feel ‘,’.join([‘VERY’]*10) strongly about adding a variable low-resolution cutoff to the completeness check (though I could add a developer option that would be hidden to muggles, I suppose).

If reflections are present/missing in some files but not others (especially low resolution reflections!), then it causes huge ripples in the output event maps.

 but thought it worth mentioning as expanding the resolution limit of a input file is not a common preprocessing step, and that this error would not uniquely occur within XCE. 

Last time I looked at the code (when Tobias and I first came across this problem so many moons ago), we added uniqueify to XCE pre-processing explicitly for this purpose — to populate ALL reflections up to a certain resolution. 
I presume this problem is that uniqueify only populated the reflections between the upper and lower limits (not between upper and infinity) so if a low resolution reflection was missing it wouldn’t have been populated, etc, etc… 
You may be able to tweak the input to uniqueify, but Tobias’ option B below is probably the solution if the input to uniqueify can’t be tweaked.

The related error messages commonly occur outside of XCE, but those reflections MUST be present or it completely f***s up the analysis.
I need to write a section on the pandda webpage about preparing data, and possibly a script to auto-populate the reflections (giant.format_mtz or some such nonsense).

Good sleuthing — by the way I have also now added functionality to pandda that prints the list of missing reflections for each file for debugging (will be in v0.2.11).

Thanks,
Nick

**Closed** 2017-11-08 10:19 UTC
Labels: bug, High
